//! Generate a deterministic BIP340 schnorr signature via the full
//! 2-of-2 FROST DKG + sign flow. Output is pasted into the Solidity
//! verifier test to prove offchain → onchain handoff works end-to-end.
//!
//! Run with: cargo run -p vouch-frost --example gen_test_vector

use rand_chacha::ChaCha20Rng;
use rand_chacha::rand_core::SeedableRng;
use std::collections::BTreeMap;
use vouch_frost::{dkg, identifier, sign};

fn main() {
    let mut rng = ChaCha20Rng::from_seed([0u8; 32]);
    let id_a = identifier(1);
    let id_b = identifier(2);

    // DKG
    let a_r1 = dkg::round1(id_a, &mut rng).unwrap();
    let b_r1 = dkg::round1(id_b, &mut rng).unwrap();
    let a_recv1: BTreeMap<_, _> = [(id_b, b_r1.package)].into();
    let b_recv1: BTreeMap<_, _> = [(id_a, a_r1.package)].into();
    let a_r2 = dkg::round2(a_r1.secret, &a_recv1).unwrap();
    let b_r2 = dkg::round2(b_r1.secret, &b_recv1).unwrap();
    let a_recv2: BTreeMap<_, _> = [(id_b, b_r2.packages[&id_a].clone())].into();
    let b_recv2: BTreeMap<_, _> = [(id_a, a_r2.packages[&id_b].clone())].into();
    let (a_key, a_pub) = dkg::finalize(&a_r2.secret, &a_recv1, &a_recv2).unwrap();
    let (b_key, _b_pub) = dkg::finalize(&b_r2.secret, &b_recv1, &b_recv2).unwrap();

    // Sign a fixed 32-byte message (BIP340 requires len == 32).
    let msg: [u8; 32] = [
        0xde, 0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef, 0xde,
        0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef, 0xde, 0xad,
        0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef,
    ];

    let (a_nonces, a_commits) = sign::commit(&a_key, &mut rng);
    let (b_nonces, b_commits) = sign::commit(&b_key, &mut rng);
    let commits: BTreeMap<_, _> = [(id_a, a_commits), (id_b, b_commits)].into();
    let pkg = sign::make_signing_package(commits, &msg).unwrap();
    let a_share = sign::sign_share(&pkg, &a_nonces, &a_key).unwrap();
    let b_share = sign::sign_share(&pkg, &b_nonces, &b_key).unwrap();
    let shares: BTreeMap<_, _> = [(id_a, a_share), (id_b, b_share)].into();
    let sig = sign::aggregate(&pkg, &shares, &a_pub).unwrap();

    a_pub
        .verifying_key()
        .verify(&msg, &sig)
        .expect("aggregated signature must verify offchain");

    let pub_bytes = a_pub.verifying_key().serialize().unwrap();
    let sig_bytes = sig.serialize().unwrap();

    // VerifyingKey::serialize() returns 33-byte compressed SEC format
    // (0x02/0x03 prefix + 32 bytes of x). BIP340 x-only is just the
    // trailing 32 bytes — the prefix is dropped because BIP340 implicitly
    // uses the even-Y interpretation of x regardless of the signing
    // pubkey's actual y parity (frost-secp256k1-tr handles the internal
    // sign flip during signing).
    assert_eq!(pub_bytes.len(), 33, "expected SEC compressed pubkey");
    let pub_x = &pub_bytes[1..];

    println!("// generated by examples/gen_test_vector.rs (deterministic seed [0; 32])");
    println!("bytes32 msg32 = 0x{};", hex::encode(msg));
    println!("uint256 pubX  = 0x{};", hex::encode(pub_x));
    println!("bytes memory sig = hex\"{}\";", hex::encode(&sig_bytes));
}
